# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true
    http_method_override: true

#when@dev:
#    _errors:
#        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
#        prefix:   /_error

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
